language: python
dist: xenial
sudo: true
python:
  - "3.6"
  - "3.7"

install:
  - travis_retry pip install -r requirements.txt pytest pytest-cov

script:
  - py.test --cov=aiodinweb

after_success:
  - bash <(curl -s https://codecov.io/bash)
